//This server_frame.java file is to create a chat server which supports text transfer. 
//The server receives connection from clients. It supports forwarding of message from client to client

import java.io.*;
import java.net.*;
import java.util.*;
import javax.swing.JOptionPane;

public class server_frame extends javax.swing.JFrame {
   ArrayList clientOutputStreams;
  ArrayList<String> users;
  Date date=new Date();
  public class ClientHandler implements Runnable{
    BufferedReader reader;
    Socket sock;
    PrintWriter client;
    BufferedReader ContentRead;
    ServerSocket serverSock;
    public ClientHandler(Socket clientSocket,PrintWriter user){
        client=user;
        try{
            sock=clientSocket;
            InputStreamReader isReader=new InputStreamReader(sock.getInputStream());
            reader=new BufferedReader(isReader);
        }catch(Exception ex){
            ta_chat.append("Unexcepted error...\n");
        }
    }
    
    @Override
    public void run(){
       String message,connect="-------------------------------------",disconnect="----------------------",chat=" ";
        String[] data;
        String str;
        try{
            while((message=reader.readLine())!=null){

                data=message.split("`");
                if(data[1].equals("is on-line now.")){
                    userAdd(data[0]);
                }else if(data[1].equals("is off on-line")){
                    userRemove(data[0]);
                }else if(data[3].equals(" ")){
                    userChat(data[0] + "`" + data[1] + "`" + data[2] + "`" + chat);
                }else if(data[3].equals("~")){
                    userChat(data[0] + "`" + data[1] + "`" + data[2] + "`" + "~");
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
            clientOutputStreams.remove(client);
        }        
       }
    }
 /**
     * Creates new form server_frame
     */
    public server_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        b_start = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_chat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat's server");

        b_start.setText("START");
        b_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_startActionPerformed(evt);
            }
        });

        ta_chat.setColumns(20);
        ta_chat.setRows(5);
        jScrollPane1.setViewportView(ta_chat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_start)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(b_start)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void b_startActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        Thread starter = new Thread(new ServerStart());
        starter.start();    
        ta_chat.append("Server started...\n");
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(server_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(server_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(server_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(server_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new server_frame().setVisible(true);
            }
        });
    }

    public class ServerStart implements Runnable 
    {
        @Override

        public void run() 
        {
            clientOutputStreams = new ArrayList();
            users = new ArrayList();  

            try 
            {
                ServerSocket serverSock = new ServerSocket(2222);
               while (true) 
               {
                 Socket clientSock = serverSock.accept();
	         PrintWriter writer = new PrintWriter(clientSock.getOutputStream(),true);
                 
	         clientOutputStreams.add(writer);

		 Thread listener = new Thread(new ClientHandler(clientSock, writer));
		 listener.start();
                }
            }
            catch (Exception ex)
            {
                ta_chat.append("Error making a connection. \n");
            }
        }
    }
    
    public void userChat(String data){
        users.add(data);
            
        tellEveryone(data);
    }
    public void userAdd(String data){
        String message, add = "has comed.", done = " ", name = data;
        users.add(name);
        if(users.size()==1){
          message=name + "`has comed.`";
          tellEveryone(message);
        }
        String[] tempList = new String[(users.size())];
        users.toArray(tempList);
      if(users.size()>1){
        for (String token:tempList) 
        {
            message = (token + "`is here.`");
            tellEveryone(message);
        }
        
        for(String token:tempList){
            message=(token + "`here`");
            tellEveryone(message);
        }
      }
   }
  
    public void userRemove (String data) 
    {
       
        String message, add = "has leaved.", done = " ", name = data;
        users.remove(name);
        message=name + "`has leaved.` ";
        tellEveryone(message);
        String[] tempList = new String[(users.size())];
        users.toArray(tempList);
        for (String token:tempList) 
        {
            message = (token + "`has comed.`");
            tellEveryone(message);
        }
    }
    
    public void tellEveryone(String message) 
    {
	Iterator it = clientOutputStreams.iterator();

        while (it.hasNext()) 
        {
            try 
            {
                PrintWriter writer = (PrintWriter) it.next();
                
		writer.println(message);
                writer.flush();
                ta_chat.setCaretPosition(ta_chat.getDocument().getLength());
            } 
            catch (Exception ex) 
            {
               ta_chat.append("Error telling everyone. \n");
            }
        } 
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton b_start;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_chat;
    // End of variables declaration                   
}
